
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 8;
  public static final int PAR_OUV = 4;
  public static final int ANTI_SLASH = 6;
  public static final int CONCAT = 12;
  public static final int AFFECT = 11;
  public static final int EOF = 0;
  public static final int OP_PLUS = 2;
  public static final int PAR_FERM = 5;
  public static final int TABLEAU = 9;
  public static final int SEP = 7;
  public static final int ENTIER = 14;
  public static final int error = 1;
  public static final int PRINT = 13;
  public static final int VIRG = 10;
  public static final int OP_FOIS = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OP_PLUS",
  "OP_FOIS",
  "PAR_OUV",
  "PAR_FERM",
  "ANTI_SLASH",
  "SEP",
  "IDENT",
  "TABLEAU",
  "VIRG",
  "AFFECT",
  "CONCAT",
  "PRINT",
  "ENTIER"
  };
}

